# Generated by Django 5.2.6 on 2025-09-18 03:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Bienvenida"),
                            ("2fa_enabled", "2FA Habilitado"),
                            ("2fa_disabled", "2FA Deshabilitado"),
                            ("event_reminder", "Recordatorio de Evento"),
                            ("event_created", "Evento Creado"),
                            ("event_updated", "Evento Actualizado"),
                            ("event_cancelled", "Evento Cancelado"),
                            ("group_request_approved", "Solicitud de Grupo Aprobada"),
                            ("group_request_rejected", "Solicitud de Grupo Rechazada"),
                            ("group_new_member", "Nuevo Miembro en Grupo"),
                            ("group_member_left", "Miembro Abandonó Grupo"),
                            ("password_reset", "Restablecimiento de Contraseña"),
                            ("account_security", "Seguridad de Cuenta"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "html_content",
                    models.TextField(
                        help_text="HTML template with Django template syntax"
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, help_text="Plain text version"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de Email",
                "verbose_name_plural": "Plantillas de Email",
            },
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True)),
                (
                    "from_email",
                    models.EmailField(
                        default="noreply@proyecto-final.com", max_length=254
                    ),
                ),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("normal", "Normal"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sending", "Enviando"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación por Email",
                "verbose_name_plural": "Notificaciones por Email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Recordatorios de eventos"
                    ),
                ),
                (
                    "event_updates",
                    models.BooleanField(
                        default=True, verbose_name="Actualizaciones de eventos"
                    ),
                ),
                (
                    "event_cancellations",
                    models.BooleanField(
                        default=True, verbose_name="Cancelaciones de eventos"
                    ),
                ),
                (
                    "group_requests",
                    models.BooleanField(
                        default=True, verbose_name="Solicitudes de grupo"
                    ),
                ),
                (
                    "group_updates",
                    models.BooleanField(
                        default=True, verbose_name="Actualizaciones de grupo"
                    ),
                ),
                (
                    "new_members",
                    models.BooleanField(default=True, verbose_name="Nuevos miembros"),
                ),
                (
                    "security_alerts",
                    models.BooleanField(
                        default=True, verbose_name="Alertas de seguridad"
                    ),
                ),
                (
                    "login_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Notificaciones de inicio de sesión"
                    ),
                ),
                (
                    "newsletter",
                    models.BooleanField(
                        default=False, verbose_name="Boletín informativo"
                    ),
                ),
                (
                    "promotional_emails",
                    models.BooleanField(
                        default=False, verbose_name="Emails promocionales"
                    ),
                ),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Inmediato"),
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                        ],
                        default="immediate",
                        max_length=20,
                        verbose_name="Frecuencia de emails",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencias de Notificación",
                "verbose_name_plural": "Preferencias de Notificación",
            },
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Tecmilenio 2FA", max_length=100)),
                ("secret_key", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo TOTP",
                "verbose_name_plural": "Dispositivos TOTP",
            },
        ),
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("1_week", "1 semana antes"),
                            ("3_days", "3 días antes"),
                            ("1_day", "1 día antes"),
                            ("2_hours", "2 horas antes"),
                            ("30_minutes", "30 minutos antes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="events.event",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recordatorio de Evento",
                "verbose_name_plural": "Recordatorios de Evento",
                "unique_together": {("event", "recipient", "reminder_type")},
            },
        ),
    ]
