# Generated by Django 5.2.6 on 2025-09-21 21:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("password_change", "Cambio de Contraseña"),
                            ("email_change", "Cambio de Email"),
                            ("phone_change", "Cambio de Teléfono"),
                            ("role_change", "Cambio de Rol"),
                            ("sensitive_data_access", "Acceso a Datos Sensibles"),
                            ("admin_operations", "Operaciones Administrativas"),
                            ("group_management", "Gestión de Grupos"),
                            ("event_management", "Gestión de Eventos"),
                            ("user_management", "Gestión de Usuarios"),
                            ("financial_operations", "Operaciones Financieras"),
                        ],
                        help_text="Operación que requiere verificación",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("email", "Verificación de Email"),
                            ("phone", "Verificación de Teléfono"),
                            ("both", "Ambas Verificaciones"),
                            ("account", "Cuenta Completamente Verificada"),
                        ],
                        help_text="Tipo de verificación requerida",
                        max_length=20,
                    ),
                ),
                (
                    "required_for_roles",
                    models.JSONField(
                        default=list,
                        help_text="Lista de roles que requieren esta verificación",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si el requerimiento está activo"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del requerimiento de verificación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Requerimiento de Verificación",
                "verbose_name_plural": "Requerimientos de Verificación",
                "db_table": "verification_requirements",
            },
        ),
        migrations.CreateModel(
            name="UserVerificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el email del usuario está verificado",
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se verificó el email",
                        null=True,
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el teléfono del usuario está verificado",
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se verificó el teléfono",
                        null=True,
                    ),
                ),
                (
                    "account_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la cuenta está completamente verificada",
                    ),
                ),
                (
                    "account_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se verificó completamente la cuenta",
                        null=True,
                    ),
                ),
                (
                    "email_verification_required",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la verificación de email es requerida",
                    ),
                ),
                (
                    "phone_verification_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la verificación de teléfono es requerida",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario asociado al estado de verificación",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Verificación de Usuario",
                "verbose_name_plural": "Estados de Verificación de Usuario",
                "db_table": "user_verification_status",
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token único para la verificación de email",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email a verificar (puede ser diferente al actual del usuario)",
                        max_length=254,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación del token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Fecha y hora de expiración del token"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se verificó el email",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si el token está activo"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Dirección IP desde donde se solicitó la verificación",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent del navegador que solicitó la verificación",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario asociado al token de verificación de email",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Verificación de Email",
                "verbose_name_plural": "Tokens de Verificación de Email",
                "db_table": "email_verification_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="email_verif_token_df7c5e_idx"),
                    models.Index(
                        fields=["user", "is_active"],
                        name="email_verif_user_id_8ea973_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="email_verif_expires_770728_idx"
                    ),
                    models.Index(fields=["email"], name="email_verif_email_16e321_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhoneVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Código de verificación de 6 dígitos", max_length=6
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número de teléfono a verificar",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de teléfono debe tener entre 9 y 15 dígitos",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación del token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Fecha y hora de expiración del token"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se verificó el teléfono",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si el token está activo"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Número de intentos de verificación"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3, help_text="Número máximo de intentos permitidos"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Dirección IP desde donde se solicitó la verificación",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent del navegador que solicitó la verificación",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario asociado al token de verificación de teléfono",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Verificación de Teléfono",
                "verbose_name_plural": "Tokens de Verificación de Teléfono",
                "db_table": "phone_verification_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="phone_verif_token_cf9668_idx"),
                    models.Index(
                        fields=["user", "is_active"],
                        name="phone_verif_user_id_cb4f8d_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="phone_verif_expires_587751_idx"
                    ),
                    models.Index(
                        fields=["phone_number"], name="phone_verif_phone_n_691ba4_idx"
                    ),
                ],
            },
        ),
    ]
