# Generated by Django 5.2.6 on 2025-09-17 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="Matrícula del estudiante (requerida solo para estudiantes y presidentes)",
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_student_id",
                        message="La matrícula debe tener el formato AL seguido de 8 dígitos",
                        regex="^AL[0-9]{8}$",
                    )
                ],
            ),
        ),
    ]
