# Generated by Django 5.2.6 on 2025-09-20 06:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Correo electrónico del usuario",
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_email",
                        message="El correo electrónico debe ser válido y pertenecer a Tecmilenio",
                        regex="^[a-zA-Z0-9.]+@tecmilenio.mx$",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token único para el restablecimiento de contraseña",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación del token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Fecha y hora de expiración del token"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se usó el token",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si el token está activo"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Dirección IP desde donde se solicitó el restablecimiento",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent del navegador que solicitó el restablecimiento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario asociado al token de restablecimiento",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Restablecimiento de Contraseña",
                "verbose_name_plural": "Tokens de Restablecimiento de Contraseña",
                "db_table": "password_reset_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="password_re_token_060a1f_idx"),
                    models.Index(
                        fields=["user", "is_active"],
                        name="password_re_user_id_75c3a8_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="password_re_expires_8e96b7_idx"
                    ),
                ],
            },
        ),
    ]
