# Generated by Django 5.2.6 on 2025-09-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Session key associated with the event",
                max_length=40,
                null=True,
            ),
        ),
    ]
