# Generated by Django 5.2.6 on 2025-09-15 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Título del evento", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Descripción detallada del evento"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("academic", "Académico"),
                            ("social", "Social"),
                            ("sports", "Deportivo"),
                            ("cultural", "Cultural"),
                            ("meeting", "Reunión"),
                            ("workshop", "Taller"),
                            ("conference", "Conferencia"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        help_text="Tipo de evento",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("cancelled", "Cancelado"),
                            ("completed", "Completado"),
                        ],
                        default="draft",
                        help_text="Estado del evento",
                        max_length=20,
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="Fecha y hora de inicio del evento"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="Fecha y hora de fin del evento"),
                ),
                (
                    "location",
                    models.CharField(help_text="Ubicación del evento", max_length=200),
                ),
                (
                    "max_attendees",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número máximo de asistentes (vacío = sin límite)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, help_text="Fecha límite de inscripción", null=True
                    ),
                ),
                (
                    "requires_registration",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el evento requiere inscripción previa",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen promocional del evento",
                        null=True,
                        upload_to="events/images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "events",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Inscrito"),
                            ("confirmed", "Confirmado"),
                            ("attended", "Asistió"),
                            ("no_show", "No asistió"),
                            ("cancelled", "Canceló"),
                        ],
                        default="registered",
                        help_text="Estado de asistencia",
                        max_length=20,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre la asistencia",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistente a Evento",
                "verbose_name_plural": "Asistentes a Eventos",
                "db_table": "event_attendees",
                "ordering": ["registration_date"],
            },
        ),
    ]
