# Generated by Django 5.2.6 on 2025-09-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                help_text="Usuario que organiza el evento",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="target_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Grupos de estudiantes objetivo (vacío = todos los grupos)",
                related_name="events",
                to="students.studentgroup",
            ),
        ),
        migrations.AddField(
            model_name="eventattendee",
            name="event",
            field=models.ForeignKey(
                help_text="Evento al que asiste",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendees",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventattendee",
            name="user",
            field=models.ForeignKey(
                help_text="Usuario que asiste al evento",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventattendee",
            unique_together={("event", "user")},
        ),
    ]
