# Generated by Django 5.2.6 on 2025-09-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="target_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Grupos estudiantiles objetivo del evento",
                related_name="events",
                to="students.studentgroup",
            ),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="event",
            field=models.ForeignKey(
                help_text="Evento al que asiste",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="events.event",
            ),
        ),
    ]
