# Generated by Django 5.2.6 on 2025-09-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Inscrito"),
                    ("confirmed", "Confirmado"),
                    ("attended", "Asistió"),
                    ("no_show", "No asistió"),
                    ("cancelled", "Cancelado"),
                    ("pending", "Pendiente de aprobación"),
                ],
                default="registered",
                help_text="Estado de asistencia",
                max_length=20,
            ),
        ),
    ]
