# Generated by Django 5.2.6 on 2025-09-21 20:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "membership_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID único de la membresía",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                        ],
                        default="pending",
                        help_text="Estado de la membresía",
                        max_length=20,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de solicitud/ingreso al grupo",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Miembro"), ("president", "Presidente")],
                        default="member",
                        help_text="Rol dentro del grupo",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresía de Grupo",
                "verbose_name_plural": "Membresías de Grupos",
                "db_table": "group_memberships",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "group_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID único del grupo estudiantil",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del grupo estudiantil",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descripción detallada del grupo"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen representativa del grupo",
                        null=True,
                        upload_to="groups/images/",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del grupo"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si el grupo está activo"
                    ),
                ),
                (
                    "max_members",
                    models.IntegerField(
                        default=50,
                        help_text="Número máximo de miembros permitidos",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("deportivo", "Deportivo"),
                            ("cultural", "Cultural"),
                            ("academico", "Académico"),
                            ("social", "Social"),
                            ("tecnologico", "Tecnológico"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        help_text="Categoría del grupo estudiantil",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo Estudiantil",
                "verbose_name_plural": "Grupos Estudiantiles",
                "db_table": "student_groups",
                "ordering": ["name"],
            },
        ),
    ]
