# Generated by Django 5.2.6 on 2025-09-15 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "tuition_number",
                    models.CharField(
                        help_text="Matrícula del estudiante",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_tuition_number",
                                message="La matrícula debe contener solo letras mayúsculas y números",
                                regex="^AL[0-9]{8}+$",
                            )
                        ],
                    ),
                ),
                (
                    "career",
                    models.CharField(help_text="Carrera que estudia", max_length=200),
                ),
                (
                    "semester",
                    models.PositiveIntegerField(
                        help_text="Semestre actual del estudiante"
                    ),
                ),
                ("enrollment_date", models.DateField(help_text="Fecha de inscripción")),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de graduación (si aplica)",
                        null=True,
                    ),
                ),
                (
                    "average_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Promedio general del estudiante",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si el estudiante está activo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
                "db_table": "students",
                "ordering": ["tuition_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del grupo (ej: Grupo A, 1er Semestre, etc.)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción del grupo", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si el grupo está activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Estudiantes",
                "verbose_name_plural": "Grupos de Estudiantes",
                "db_table": "student_groups",
                "ordering": ["name"],
            },
        ),
    ]
