# Generated by Django 5.2.6 on 2025-09-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="user",
            field=models.ForeignKey(
                help_text="Usuario miembro del grupo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="president",
            field=models.ForeignKey(
                blank=True,
                help_text="Presidente del grupo",
                limit_choices_to={"role": "president"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                help_text="Grupo al que pertenece",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="students.studentgroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together={("user", "group")},
        ),
    ]
