# Generated by Django 5.2.6 on 2025-09-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="Usuario asociado al estudiante",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="president",
            field=models.OneToOneField(
                blank=True,
                help_text="Presidente del grupo",
                limit_choices_to={"role": "president"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_group",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo al que pertenece el estudiante",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.studentgroup",
            ),
        ),
    ]
